import reflex as rx
from Tocc.styles.styles import Size, Spacing
from Tocc.styles.colors import Color, TextColor

def services() -> rx.Component:
    return rx.vstack(
        rx.vstack(
            rx.text("Servicios integrales a la medida y su necesidad", size="8", font_weight="bold"),
            rx.text("Ofrecemos una amplia gama de servicios para satisfacer tus necesidades tecnológicas.", size="5"),
            spacing="2",
            width="100%",
            padding_x=Size.DEFAULT.value,
            padding_y=Size.DEFAULT.value,
            border_radius="10px",
            bg=Color.LILA.value,
            align="center",
        ),
        rx.hstack(
            rx.image(
                src="/desarrollo.png",
                alt="Desarrollo software y soluciones digitales",
                width="50%",
                height="auto",
                padding=Size.DEFAULT.value,
                border_radius="10px",
            ),
            rx.vstack(
                rx.text("Desarrollo de software y soluciones digitales", size="5", font_weight="bold"),
                rx.text("Desarrollo de software a la medida", size="3"),
                rx.text("Desarrollo web y móviles", size="3"),
                rx.text("Creación de páginas web", size="3"),
                width="50%",
                height="100%",
                justify="center",
                align="center",
                text_align="center",
                padding=Size.DEFAULT.value,
            ),
            width="100%",
            bg=Color.LILA.value,
            border_radius="10px",
        ),
        rx.hstack(
            rx.vstack(
                rx.text("Ciberseguridad y protección de datos", size="5", font_weight="bold"),
                rx.text("Auditorías de seguridad informatica", size="3"),
                rx.text("Gestion de identidad y accesos", size="3"),
                rx.text("Respaldo y recuperacion de datos", size="3"),
                width="50%",
                height="100%",
                justify="center",
                align="center",
                text_align="center",
                padding=Size.DEFAULT.value,
            ),
            rx.image(
                src="/ciberseguridad.png",
                alt="Ciberseguridad y protección de datos",
                width="50%",
                height="auto",
                padding=Size.DEFAULT.value,
                border_radius="10px",
            ),
            width="100%",
            bg=Color.LILA.value,
            border_radius="10px",
        ),
        rx.hstack(
            rx.image(
                src="/asesorias.png",
                alt="Consultorías y asesorías ",
                width="50%",
                height="auto",
                padding=Size.DEFAULT.value,
                border_radius="10px",
            ),
            rx.vstack(
                rx.text("Consultorías y asesorías", size="5", font_weight="bold"),
                rx.text("Consultoria en transformacion digital", size="3"),
                rx.text("Arquitectura de sofware y cloud computing", size="3"),
                rx.text("Optimización de infraestructura IT", size="3"),
                rx.text("Asesoría legal en tecnología y protección de datos", size="3"),
                rx.text ("Contractos tecnologicos y propiedad intelectual", size="3"),
                width="50%",
                height="100%",
                justify="center",
                align="center",
                text_align="center",
                padding=Size.DEFAULT.value,
            ),
            width="100%",
            bg=Color.LILA.value,
            border_radius="10px",
        ),
        rx.hstack(
            rx.vstack(
                rx.text("Soluciones de hardware y equipamiento tecnológico", size="5", font_weight="bold"),
                rx.text("Soporte tecnico y mantenimiento", size="3"),
                rx.text("Capacitacion en tecnologia y seguridad digital", size="3"),
                rx.text("Mantenimiento preventivo y correctivo de equipos", size="3"),
                rx.text("Ensamblaje de PC a la medida", size="3"),
                rx.text("Instalación y configuración de oficinas tecnológicas", size="3"),
                rx.text("Montaje de camaras de seguridad y sistemas de vigilancia", size="3"),
                rx.text("Optimización y configuración de redes y módems", size="3"),
                rx.text("Asesoramiento técnico en hardware y tecnología", size="3"),
                rx.text("Venta de periféricos y equipos tecnológicos", size="3"),
                width="50%",
                height="100%",
                justify="center",
                align="center",
                text_align="center",
                padding=Size.DEFAULT.value,
            ),
            rx.image(
                src="/harware.png",
                alt="Soluciones de hardware y equipamiento tecnológico",
                width="50%",
                height="auto",
                padding=Size.DEFAULT.value,
                border_radius="10px",
            ),
            width="100%",
            bg=Color.LILA.value,
            border_radius="10px",
        ),
        width="100%",
    )
